#!/usr/bin/env bash

function printerr() {
    local err_msg="$*"

    [[ -z "${file}" ]] || err_msg+=" (${file})"
    printf "ERROR: %s\n" "${err_msg}" >&2
}

function get_value() {
    local file=$1
    local key=$2

    yq r $file $key
}

function validate_value() {
    local file=$1
    local key=$2
    local value=$(get_value $file $key | tr -d [:space:])

    if [[ -z "$value" ]]; then
        printerr "Missing value for ${key@Q}"
        return 1
    fi
}

