#!/usr/bin/env bash

set -e

### General Functions ###

function exit_error() {
    echo "--------- Captured output ---------"
    echo "${output}"
    echo "-----------------------------------"
    echo "ERROR: $*"
    exit 1
}

function print_test() {
    echo "TEST: $*"
}

function reset_git() {
    git checkout -- releases/*
    git reset --keep "${base_commit}" > /dev/null
}

function _make() {
    declare -g output
    output=$(make "${@}" dryrun=true 2>&1)
    return "$?"
}

# In case we're targeting a branch, the commands will fail, so remove it for testing
function sanitize_branch() {
    if grep 'branch:' "releases/v${VERSION}.yaml" > /dev/null ; then
        sed -i '/^branch:.*/d' "releases/v${VERSION}.yaml"
        git commit -a -m "Remove branch or make release will fail" > /dev/null
    fi
}

