---
name: Branch Checks

on:
  pull_request:

jobs:
  target_branch:
    name: PR targets branch
    runs-on: ubuntu-latest
    steps:
      - name: Check that the PR targets release-0.13
        if: ${{ github.base_ref != 'release-0.13' }}
        run: exit 1
