---
name: Release the Target Release

on:
  push:
    branches:
      - devel
    paths:
      - 'releases/**'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: read

jobs:
  release:
    name: Release
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3

      - name: Perform the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
        run: make do-release
