---
name: Testing

on:
  pull_request:

jobs:
  release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Test the `make release` command
        run: make test-release
