---
name: Testing

on:
  pull_request:

jobs:
  release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0

      - name: Test the `make release` command
        run: make test-release
