---
name: Testing

permissions:
  actions: write
  contents: read

on:
  pull_request:

jobs:
  skip-check:
    name: Run tests except on release
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf
        with:
          paths_ignore: '["releases/**"]'

  command:
    name: Command
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ['do-release', 'release']

    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Test the `make ${{ matrix.command }}` command
        env:
          # Needed for testing as we're running validations which hit the GH API rate limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test-${{ matrix.command }}

  entire-release:
    name: Entire release process
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['100.0.0-m0', '100.0.0-rc0']

    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      # Needed to properly build multi-arch Shipyard images when branching out
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
      - name: Set up buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

      - name: Test the entire release
        env:
          # Needed for testing as we're running validations which hit the GH API rate limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test-entire-release VERSION="${{ matrix.version }}"
