---
name: Testing

permissions:
  actions: write
  contents: read

on:
  pull_request:

jobs:
  skip-check:
    name: Run tests except on release
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f11521568414503656a5af807dc3018c012552c4
        with:
          paths_ignore: '["releases/**"]'

  release:
    name: Make release
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Test the `make release` command
        env:
          # Needed for testing as we're running validations which hit the GH API rate limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test-release

  entire-release:
    name: Entire release process
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['100.0.0-m0', '100.0.0-rc0']

    steps:
      - name: Check out the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      # Needed to properly build multi-arch Shipyard images when branching out
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - name: Set up buildx
        uses: docker/setup-buildx-action@95cb08cb2672c73d4ffd2f422e6d11953d2a9c70

      - name: Test the entire release
        env:
          # Needed for testing as we're running validations which hit the GH API rate limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test-entire-release VERSION="${{ matrix.version }}"
