---
name: Testing

on:
  pull_request:

jobs:
  release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0

      - name: Test the `make release` command
        run: make test-release
