---
name: Validation

on:
  pull_request:
    # Unlabeled is needed when `dependent` label is removed, to re-validate the release.
    types: [unlabeled, opened, synchronize, reopened]

permissions: {}

jobs:
  yamls:
    name: Release YAMLs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Validate release YAMLs
        run: make validate

  # This job runs the script in "dryrun" mode, not doing any changes to the repo.
  # This should make sure the script at least works as intended (given a valid yaml).
  release:
    name: Dry-run the Release
    needs: yamls
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Create the release in dry-run mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: make do-release DRY_RUN=true
